=== 日志

Spring Boot在所有内部日志中使用Commons Logging，但对底层日志的实现保持开放。为Java Util Logging、Log4J2和Logback提供了默认配置。在每一种情况下，记录器都被预设为使用控制台输出，也可以选择文件输出。

默认情况下，如果你使用 "启动器"，Logback被用来做日志记录。适当的Logback路由也包括在内，以确保使用Java Util Logging、Commons Logging、Log4J或SLF4J的依赖库都能正确工作。
====
有很多适用于Java的日志框架。如果上面的列表看起来很混乱，请不要担心。一般来说，你不需要改变你的日志依赖，Spring Boot的默认值就很好用。
====
====
当你把你的应用程序部署到一个servlet容器或应用服务器时，用Java Util Logging API执行的日志不会被传送到你的应用程序的日志中。这可以防止由容器或其他已经部署到它的应用程序执行的日志出现在你的应用程序的日志中。
====

==== 日志格式
默认的日志格式是这样的
....
2019-03-05 10:57:51.112  INFO 45469 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/7.0.52
2019-03-05 10:57:51.253  INFO 45469 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-03-05 10:57:51.253  INFO 45469 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1358 ms
2019-03-05 10:57:51.698  INFO 45469 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2019-03-05 10:57:51.702  INFO 45469 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
....
它包含以下内容的输出

* 日期和时间，精度为毫秒级，易于分类。
* 日志等级: ERROR, WARN, INFO, DEBUG, or TRACE.
* 进程ID
* 一个分隔符 ： ---
* 线程名称：包含在方括号中（为了控制台输出可能会被截断）。
* 记录仪名称：这通常是源类名称（通常是缩写）。
* 日志的内容

====
LogBack没有FAIL级别，它被映射到ERROR
====

==== 控制台输出
默认的日志配置是在写信息的时候向控制台回音。默认情况下，ERROR级、WARN级和INFO级的信息被记录下来。你也可以通过用--调试标志启动你的应用程序来启用 "DEBUG "模式。

----
java -jar myapp.jar --debug
----
====
你也可以在application.properties中指定debug = true
====
当调试模式被启用时，选择的核心记录器（嵌入式容器、Hibernate和Spring Boot）被配置为输出更多信息。启用调试模式并不能将你的应用程序配置为以DEBUG级别记录所有信息。

另外，你可以用--trace标志（或在application.properties中的trace=true）来启动你的应用程序，启用 "跟踪 "模式。这样做可以为选定的核心记录器（嵌入式容器、Hibernate模式生成和整个Spring组合）实现跟踪记录。

*彩色编码的输出*

如果你的终端支持ANSI，就会使用彩色输出来帮助阅读。你可以将spring.output.ansi.enabled设置为一个支持的值来覆盖自动检测。

颜色编码是通过使用%clr转换词配置的。在其最简单的形式下，转换器根据日志级别对输出进行着色，如下例所示。

....
%clr(%5p)
....
以下是各个级别对应的颜色
|===
| level| color
|FAIL|Red
|ERROR|Red
|WARN|Yellow
|INFO|Green
|DEBUG|Green
|TRACE|Green
|===

另外，你也可以通过为转换提供一个选项来指定应该使用的颜色或样式。例如，要使文本为黄色，请使用以下设置。
....
%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow}
....
以下是支持的颜色

* blue
* cyan
* faint
* green
* magenta
* red
* yellow

==== 文件输出
默认情况下，Spring Boot只向控制台记录日志，不写日志文件。如果你想在控制台输出之外写日志文件，你需要设置logging.file.name或logging.file.path属性（例如，在你的application.properties中）。

下表显示了logging.*属性如何被一起使用。
|===
|*logging.file.name*|*loggingl.file.path*|*输出案例*|*描述*
|无|无|无|仅在控制台输出
|my.log|无|my.log|写入指定的日志文件。名称可以是一个确切的位置，也可以是与当前目录的相对位置。
|无|/var/log|/var/log/*.log|将spring.log写到指定目录。名称可以是准确的位置，也可以是与当前目录的相对位置。
|===

当日志文件达到10MB时就会轮换，与控制台输出一样，默认情况下记录ERROR级、WARN级和INFO级信息。
====
日志属性独立于实际的日志基础设施。因此，特定的配置键（如Logback的logback.configurationFile）不由spring Boot管理。
====

==== 文件轮换
如果你使用Logback，可以使用你的application.properties或application.yaml文件来微调日志轮换设置。对于所有其他的日志系统，你需要自己直接配置轮换设置（例如，如果你使用Log4J2，那么你可以添加一个log4j2.xml或log4j2-spring.xml文件）。

支持以下轮换策略属性。

|===
|名称|描述
|logging.logback.rollingpolicy.file-name-pattern|用于创建日志档案的文件名模式。
|logging.logback.rollingpolicy.clean-history-on-start|如果应用程序启动时应进行日志归档清理。
|logging.logback.rollingpolicy.max-file-size|日志文件归档前的最大尺寸。
|logging.logback.rollingpolicy.total-size-cap|日志档案在被删除前的最大尺寸。
|logging.logback.rollingpolicy.max-history|要保留的归档日志文件的最大数量（默认为7）。
|===

==== 日志等级

所有支持的日志系统都可以通过使用logging.level.<logger-name>=<level>在Spring环境中（例如，在application.properties中）设置日志器级别，其中级别是TRACE、DEBUG、INFO、WARN、ERROR、FATAL或OFF之一。根记录器可以通过使用logging.level.root进行配置。

下面的例子显示了application.properties中潜在的日志设置。
----
logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "error"
----
也可以使用环境变量来设置日志级别。例如，LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG将设置org.springframework.web为DEBUG。
====
上述方法只适用于包级日志。由于放松的绑定总是将环境变量转换为小写，所以不可能用这种方式为单个类配置日志。如果你需要为一个类配置日志，你可以使用SPRING_APPLICATION_JSON变量。
====

==== 日志组

能够将相关的日志记录器分组，以便同时对它们进行配置，这通常很有用。例如，你可能通常会改变所有Tomcat相关日志记录器的日志级别，但你不容易记住顶级包。

为了帮助解决这个问题，Spring Boot允许你在Spring环境中定义日志组。例如，你可以通过在application.properties中添加 "tomcat "组来定义它。
----
logging:
  group:
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"

----
一旦定义，就可以用一行字来改变组中所有记录仪的级别。

----
logging:
  level:
    tomcat: "trace"

----
Spring Boot包括以下预定义的日志组，可以开箱即用。
|===
|组名称|包含的类
|web|org.springframework.core.codec, org.springframework.http, org.springframework.web, org.springframework.boot.actuate.endpoint.web, org.springframework.boot.web.servlet.ServletContextInitializerBeans
|sql|org.springframework.jdbc.core, org.hibernate.SQL, org.jooq.tools.LoggerListener
|===

==== 使用日志关闭回调

In order to release logging resources when your application terminates, a shutdown hook that will trigger log system cleanup when the JVM exits is provided. This shutdown hook is registered automatically unless your application is deployed as a war file. If your application has complex context hierarchies the shutdown hook may not meet your needs. If it does not, disable the shutdown hook and investigate the options provided directly by the underlying logging system. For example, Logback offers context selectors which allow each Logger to be created in its own context. You can use the logging.register-shutdown-hook property to disable the shutdown hook. Setting it to false will disable the registration. You can set the property in your application.properties or application.yaml file:

为了在你的应用程序终止时释放日志资源，我们提供了一个关机钩子，它将在JVM退出时触发日志系统清理。这个关机钩子是自动注册的，除非你的应用程序是以战争文件的形式部署。如果你的应用程序有复杂的上下文层次结构，关闭钩子可能无法满足你的需求。如果不能，请禁用关机钩子，并研究底层日志系统直接提供的选项。例如，Logback提供了上下文选择器，允许在其自身的上下文中创建每个记录器。你可以使用logging.register-shutdown-hook属性来禁用关机钩。将其设置为false将禁用注册。你可以在你的application.properties或application.yaml文件中设置该属性。

----
logging:
  register-shutdown-hook: false
----

==== 自定义日志配置
各种日志系统可以通过在classpath上包括适当的库来激活，并且可以通过在classpath的根部或在以下Spring环境属性指定的位置提供一个合适的配置文件来进一步定制：logging.config。

您可以通过使用 org.springframework.boot.logging.LoggingSystem 系统属性来强制 Spring Boot 使用特定的日志系统。该值应该是LoggingSystem实现的完全限定类名称。您还可以通过使用none的值来完全禁用Spring Boot的日志配置。

====
由于日志是在创建ApplicationContext之前初始化的，所以不可能从Spring @Configuration文件中的@PropertySources控制日志。改变日志系统或完全停用它的唯一方法是通过系统属性。
====
根据你的日志系统，会加载以下文件。
|===
|日志系统|配置文件
|Logback|logback-spring.xml, logback-spring.groovy, logback.xml, or logback.groovy
|Log4j2|log4j2-spring.xml or log4j2.xml
|JDK (Java Util Logging)|logging.properties
|===

====
在可能的情况下，我们建议你对你的日志配置使用-spring的变体（例如，logback-spring.xml而不是logback.xml）。如果你使用标准配置位置，Spring不能完全控制日志初始化。
====
[warning]
====
当从 "可执行的jar "中运行时，Java Util Logging有一些已知的类加载问题，会导致问题。如果可能的话，我们建议你在从 "可执行的jar "中运行时避免它。
====

[quote]
____
详情请看原文档 
____

所有支持的日志系统在解析其配置文件时都可以查阅系统属性。例子见spring-boot.jar中的默认配置。

====
如果你想在日志属性中使用占位符，你应该使用Spring Boot的语法而不是底层框架的语法。值得注意的是，如果你使用Logback，你应该使用:作为属性名称和其默认值之间的分隔符，而不是使用:-。
====
====
你可以只通过覆盖 LOG_LEVEL_PATTERN（或 Logback 的 logging.pattern.level）来向日志行添加 MDC 和其他临时内容。例如，如果你使用 logging.pattern.level=user:%X{user} %5p，那么默认的日志格式包含 "user "的 MDC 条目，如果它存在的话，如下例所示。
....
2019-08-30 12:30:04.031 user:someone INFO 22174 --- [  nio-8080-exec-0] demo.Controller
Handling authenticated request
....
====