=== spring application
SpringApplication类提供了一种方便的方式来引导从main()方法中启动的Spring应用程序。在许多情况下，你可以委托给静态的SpringApplication.run方法，如下面的例子中所示。
[source,java]
----
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MyApplication {

    public static void main(String[] args) {
        SpringApplication.run(MyApplication.class, args);
    }

}

----
当你的应用程序启动时，你应该看到类似于以下的输出。
....
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::   v2.7.0

2021-02-03 10:33:25.224  INFO 17321 --- [           main] o.s.b.d.s.s.SpringApplicationExample    : Starting SpringApplicationExample using Java 1.8.0_232 on mycomputer with PID 17321 (/apps/myjar.jar started by pwebb)
2021-02-03 10:33:25.226  INFO 17900 --- [           main] o.s.b.d.s.s.SpringApplicationExample    : No active profile set, falling back to default profiles: default
2021-02-03 10:33:26.046  INFO 17321 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-02-03 10:33:26.054  INFO 17900 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-02-03 10:33:26.055  INFO 17900 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.41]
2021-02-03 10:33:26.097  INFO 17900 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-02-03 10:33:26.097  INFO 17900 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 821 ms
2021-02-03 10:33:26.144  INFO 17900 --- [           main] s.tomcat.SampleTomcatApplication         : ServletContext initialized
2021-02-03 10:33:26.376  INFO 17900 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-02-03 10:33:26.384  INFO 17900 --- [           main] o.s.b.d.s.s.SpringApplicationExample    : Started SampleTomcatApplication in 1.514 seconds (JVM running for 1.823)
....
默认情况下，会显示INFO日志信息，包括一些相关的启动细节，比如启动应用程序的用户。如果你需要一个INFO以外的日志级别，你可以设置它，如日志级别中所述。应用程序的版本是通过主应用程序类的包的实现版本来确定的。可以通过设置spring.main.log-startup-info为false来关闭启动信息记录。这也将关闭应用程序的活动配置文件的日志记录。
====
为了在启动过程中增加额外的日志记录，你可以在SpringApplication的子类中覆盖logStartupInfo(boolean)。
====
==== 启动失败
如果你的应用程序无法启动，注册的FailureAnalyzers就有机会提供一个专门的错误信息和一个具体的行动来解决问题。例如，如果你在8080端口上启动一个网络应用，而该端口已经被使用，你应该看到类似于下面的消息。
....
***************************
APPLICATION FAILED TO START
***************************

Description:

Embedded servlet container failed to start. Port 8080 was already in use.

Action:

Identify and stop the process that is listening on port 8080 or configure this application to listen on another port.
....
====
Spring Boot提供了许多FailureAnalyzer实现，你也可以添加自己的。
====
如果没有故障分析器能够处理异常，你仍然可以显示完整的条件报告以更好地了解出错的原因。要做到这一点，你需要为org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener启用调试属性或启用DEBUG日志。

例如，如果你通过使用java -jar来运行你的应用程序，你可以启用调试属性，如下。
----
$ java -jar myproject-0.0.1-SNAPSHOT.jar --debug
----
==== 懒加载
SpringApplication允许应用程序被懒加载。当懒加载启用时，Bean会在需要时被创建，而不是在应用程序启动时。因此，启用懒加载可以减少应用程序的启动时间。在一个Web应用程序中，启用懒加载将导致许多与Web相关的Bean在收到HTTP请求之前不会被初始化。

懒加载的一个缺点是，它可以延迟发现应用程序的问题。如果一个配置错误的Bean懒加载了，那么在启动过程中就不会再出现故障，问题只有在Bean被初始化时才会显现出来。还必须注意确保JVM有足够的内存来容纳应用程序的所有Bean，而不仅仅是那些在启动期间被初始化的Bean。由于这些原因，默认情况下不启用懒加载，建议在启用懒加载之前对JVM的堆大小进行微调。

懒加载可以通过SpringApplicationBuilder的lazyInitialization方法或SpringApplication的setLazyInitialization方法以编程方式启用。另外，也可以使用spring.main.lazy-initialization属性来启用，如下例所示。

``
spring.main.lazy-initialization=true
``
====
如果你想禁用某些Bean的懒加载，而对应用程序的其他部分使用懒加载，你可以使用@Lazy(false)注解将它们的懒加载属性明确地设置为false。
====

==== 定制Banner

启动时打印的标语可以通过在classpath中添加banner.txt文件或将spring.banner.location属性设置为此类文件的位置来改变。如果该文件的编码不是UTF-8，你可以设置spring.banner.charset。除了文本文件外，你还可以在classpath中添加banner.gif、banner.jpg或banner.png图像文件，或者设置spring.banner.image.location属性。图像被转换成ASCII艺术表现形式，并打印在任何文本横幅之上。

在你的banner.txt文件中，你可以使用环境中可用的任何键，以及以下任何占位符。

|====
|占位符|描述
|${application.version}|你的应用程序的版本号，如MANIFEST.MF中所声明的。例如，Implementation-Version: 1.0被打印为1.0。

|${application.formatted-version}|你的应用程序的版本号，正如在MANIFEST.MF中声明的那样，并以格式化的方式显示（用括号包围，以v为前缀）。例如（v1.0）。

|${spring-boot.version} |你正在使用的Spring Boot版本。例如，2.7.0。

|${spring-boot.formatted-version} |您正在使用的Spring Boot版本，格式化显示（用括号包围，以v为前缀）。例如（v2.7.0）。

|${Ansi.NAME} (or 

${AnsiColor.NAME}, 

${AnsiBackground.NAME}, 

${AnsiStyle.NAME})
|其中NAME是一个ANSI转义代码的名称。详见AnsiPropertySource。

|${application.title}|你的应用程序的标题，如MANIFEST.MF中声明的那样。例如，实施-标题。MyApp被打印为MyApp。
|====

====
如果你想以编程方式生成一个横幅，可以使用SpringApplication.setBanner(..)方法。使用org.springframework.boot.Banner接口并实现你自己的printBanner()方法。
====
你还可以使用spring.main.banner-mode属性来决定横幅是否必须打印在System.out上（console），发送至配置的记录器（log），或者根本不产生（off）。

打印的横幅被注册为一个单子Bean，名称如下：springBootBanner。
====
${application.version}和${application.formatted-version}属性仅在您使用Spring Boot启动器时可用。如果您运行一个未打包的jar并使用java -cp <classpath> <mainclass>启动它，这些值将不会被解决。

这就是为什么我们建议你总是使用java org.springframework.boot.loader.JarLauncher来启动未打包的jar。这将在构建classpath和启动你的应用程序之前初始化application.* banner变量。
====
==== 定制SpirngBottApplication

如果SpringApplication的默认值不符合你的口味，你可以创建一个本地实例并对其进行自定义。例如，要关闭横幅，你可以这样写。
[source,java]
----
import org.springframework.boot.Banner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MyApplication {

    public static void main(String[] args) {
        SpringApplication application = new SpringApplication(MyApplication.class);
        application.setBannerMode(Banner.Mode.OFF);
        application.run(args);
    }

}
----
====
传递给SpringApplication的构造函数参数是Spring Bean的配置源。在大多数情况下，这些是对@Configuration类的引用，但它们也可以直接引用@Component类。
====
也可以通过使用application.properties文件来配置SpringApplication。详见外部化配置。

关于配置选项的完整列表，请参见SpringApplication Javadoc。


==== 流式构造API

如果你需要建立一个ApplicationContext层次结构（具有父/子关系的多个上下文），或者你更喜欢使用 "流"构建器API，你可以使用SpringApplicationBuilder。

SpringApplicationBuilder让你把多个方法调用串联起来，并包括父子方法，让你创建一个层次结构，如下例所示。
[source,java]
----
new SpringApplicationBuilder()
        .sources(Parent.class)
        .child(Application.class)
        .bannerMode(Banner.Mode.OFF)
        .run(args);
----
====
在创建 ApplicationContext 层次结构时有一些限制。例如，Web组件必须包含在子上下文中，而且父上下文和子上下文都使用相同的环境。详细内容请参见SpringApplicationBuilder Javadoc。
====
==== 应用可用性
在平台上部署时，应用程序可以使用Kubernetes Probes等基础设施向平台提供有关其可用性的信息。Spring Boot包括对常用的 "liveness "和 "readiness "可用性状态的开箱即用的支持。如果你使用Spring Boot的 "执行器 "支持，那么这些状态将作为健康端点组暴露出来。

此外，你还可以通过将ApplicationAvailability接口注入到你自己的Bean中来获得可用性状态。

*存活状态*

一个应用程序的 "Liveness "状态告诉我们它的内部状态是否允许它正常工作，或者在当前失败的情况下自行恢复。一个破碎的 "Liveness "状态意味着应用程序处于无法恢复的状态，基础设施应该重新启动该应用程序。
====
一般来说，"Liveness "状态不应该基于外部检查，比如健康检查。如果是这样，一个失败的外部系统（数据库、Web API、外部缓存）会引发整个平台的大规模重启和级联故障。
====
Spring Boot应用程序的内部状态大多由Spring ApplicationContext表示。如果应用程序上下文已成功启动，Spring Boot就认为应用程序处于有效状态。一旦上下文被刷新，应用程序就被认为是活的，见Spring Boot应用程序生命周期和相关应用程序事件。

*预备状态*

一个应用程序的 "准备就绪 "状态告诉人们该应用程序是否准备好处理流量。失败的 "准备就绪 "状态告诉平台，它暂时不应该将流量发送到该应用程序。这通常发生在启动期间，当CommandLineRunner和ApplicationRunner组件被处理时，或者在任何时候，如果应用程序决定它对额外的流量太忙。

一旦应用程序和命令行运行器被调用，就认为应用程序已经准备好了，见Spring Boot应用程序生命周期和相关应用程序事件。

====
预计在启动期间运行的任务应该由CommandLineRunner和ApplicationRunner组件执行，而不是使用Spring组件的生命周期回调，如@PostConstruct。
====
*管理应用程序的可用性状态*

应用程序组件可以通过注入ApplicationAvailability接口并调用其上的方法，在任何时候检索当前的可用性状态。更多时候，应用程序会想要监听状态更新或更新应用程序的状态。

例如，我们可以把应用程序的 "准备就绪 "状态导出到一个文件，这样Kubernetes的 "exec Probe "就可以查看这个文件。
[source,java]
----
import org.springframework.boot.availability.AvailabilityChangeEvent;
import org.springframework.boot.availability.ReadinessState;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

@Component
public class MyReadinessStateExporter {

    @EventListener
    public void onStateChange(AvailabilityChangeEvent<ReadinessState> event) {
        switch (event.getState()) {
        case ACCEPTING_TRAFFIC:
            // create file /tmp/healthy
            break;
        case REFUSING_TRAFFIC:
            // remove file /tmp/healthy
            break;
        }
    }

}


----
我们还可以更新应用程序的状态，当应用程序中断而无法恢复时。
[source,java]
----
import org.springframework.boot.availability.AvailabilityChangeEvent;
import org.springframework.boot.availability.LivenessState;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Component;

@Component
public class MyLocalCacheVerifier {

    private final ApplicationEventPublisher eventPublisher;

    public MyLocalCacheVerifier(ApplicationEventPublisher eventPublisher) {
        this.eventPublisher = eventPublisher;
    }

    public void checkLocalCache() {
        try {
            // ...
        }
        catch (CacheCompletelyBrokenException ex) {
            AvailabilityChangeEvent.publish(this.eventPublisher, ex, LivenessState.BROKEN);
        }
    }

}


----
====  应用程序事件和监听器

除了常见的Spring框架事件，如ContextRefreshedEvent，SpringApplication还会发送一些额外的应用事件。
====
有些事件实际上是在ApplicationContext创建之前被触发的，所以你不能以@Bean的形式为这些事件注册一个监听器。你可以用SpringApplication.addListeners(...)方法或SpringApplicationBuilder.listeners(...)方法注册它们。
如果你希望这些监听器被自动注册，无论应用程序是以何种方式创建的，你可以在你的项目中添加一个META-INF/spring.plants文件，并通过使用org.springframework.context.ApplicationListener键来引用你的监听器，如下面的例子中所示。

....
org.springframework.context.ApplicationListener=com.example.project.MyListener
....

====

当你的应用程序运行时，应用程序事件按以下顺序发送：

. ApplicationStartingEvent在运行开始时被发送，但在任何处理之前，除了监听器和初始化器的注册之外。
. 当已知将在上下文中使用的环境，但在创建上下文之前，将发送一个ApplicationEnvironmentPreparedEvent。
. 当 ApplicationContext 被准备好并且 ApplicationContextInitializers 被调用，但在任何 bean 定义被加载之前，ApplicationContextInitializedEvent 被发送。
. ApplicationPreparedEvent在刷新开始前但在Bean定义被加载后被发送。
. ApplicationStartedEvent在上下文被刷新之后，但在任何应用程序和命令行运行程序被调用之前被发送。
. 紧接着发送一个可用性变化事件（AvailabilityChangeEvent），并注明LivenessState.CORRECT，以表明应用程序被认为是有效的。
. ApplicationReadyEvent在任何应用程序和命令行运行程序被调用之后被发送。
. 紧接着发送一个带有ReadinessState.ACCEPTING_TRAFFIC的AvailabilityChangeEvent，以表明应用程序已经准备好为请求提供服务。
. 如果在启动时出现异常，将发送一个ApplicationFailedEvent。

上面的列表只包括与SpringApplication绑定的SpringApplicationEvents。除此以外，以下事件也会在ApplicationPreparedEvent之后和ApplicationStartedEvent之前发布。

* WebServerInitializedEvent是在WebServer准备好后发送的。ServletWebServerInitializedEvent和ReactiveWebServerInitializedEvent分别是Servlet和reactive的变体。
* 当ApplicationContext被刷新时，会发送一个ContextRefreshedEvent。

====
你通常不需要使用应用程序事件，但知道它们的存在会很方便。在内部，Spring Boot使用事件来处理各种任务。
====

====
事件监听器不应该运行潜在的冗长任务，因为它们默认是在同一个线程中执行。考虑使用应用程序和命令行运行器来代替。
====

应用程序事件是通过使用Spring框架的事件发布机制来发送的。这种机制的一部分是确保发布给子上下文中的监听器的事件也会发布给任何祖先上下文中的监听器。因此，如果你的应用程序使用SpringApplication实例的层次结构，一个监听器可能会收到同一类型应用程序事件的多个实例。

为了让你的监听器能够区分其上下文的事件和后代上下文的事件，它应该请求其应用程序上下文被注入，然后将注入的上下文与事件的上下文进行比较。上下文可以通过实现ApplicationContextAware来注入，或者，如果监听器是一个Bean，可以通过使用@Autowired来注入。

==== web环境
一个SpringApplication试图代表你创建正确类型的ApplicationContext。用来确定WebApplicationType的算法如下。

* 如果有Spring MVC，就会使用AnnotationConfigServletWebServerApplicationContext。
* 如果不存在Spring MVC而存在Spring WebFlux，就会使用AnnotationConfigReactiveWebServerApplicationContext。
* 否则，将使用AnnotationConfigApplicationContext。

这意味着，如果你在同一个应用程序中使用Spring MVC和Spring WebFlux的新WebClient，Spring MVC将被默认使用。你可以通过调用setWebApplicationType(WebApplicationType)轻松地覆盖这一点。

也可以通过调用setApplicationContextClass(...)来完全控制使用的ApplicationContext类型。
====
当在JUnit测试中使用SpringApplication时，通常需要调用setWebApplicationType(WebApplicationType.NONE)。
====
==== 访问应用程序的参数
如果你需要访问传递给SpringApplication.run(...)的应用程序参数，你可以注入一个org.springframework.boot.ApplicationArguments Bean。ApplicationArguments接口提供了对原始的String[]参数以及经过解析的选项和非选项参数的访问，如下面的例子中所示。
[source,java]
----
import java.util.List;

import org.springframework.boot.ApplicationArguments;
import org.springframework.stereotype.Component;

@Component
public class MyBean {

    public MyBean(ApplicationArguments args) {
        boolean debug = args.containsOption("debug");
        List<String> files = args.getNonOptionArgs();
        if (debug) {
            System.out.println(files);
        }
        // if run with "--debug logfile.txt" prints ["logfile.txt"]
    }

}
----
====
Spring Boot还向Spring环境注册了一个CommandLinePropertySource。这让你也可以通过使用@Value注解来注入单个应用参数。
====
==== 使用 ApplicationRunner 或 CommandLineRunner
如果你需要在SpringApplication启动后运行一些特定的代码，你可以实现ApplicationRunner或CommandLineRunner接口。这两个接口的工作方式相同，并提供一个单一的运行方法，该方法在SpringApplication.run(...)完成之前被调用。
====
这个合同很适合那些应该在应用程序启动后但在其开始接受流量之前运行的任务。
====
CommandLineRunner接口提供了对作为字符串数组的应用程序参数的访问，而ApplicationRunner使用前面讨论的ApplicationArguments接口。下面的例子显示了一个带有运行方法的CommandLineRunner。
[source,java]
----
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class MyCommandLineRunner implements CommandLineRunner {

    @Override
    public void run(String... args) {
        // Do something...
    }

}
----
如果定义了几个必须以特定顺序调用的CommandLineRunner或ApplicationRunner Bean，你可以额外实现org.springframework.core.Ordered接口或使用org.springframework.core.annotation.Order注解。

==== 应用程序退出
每个SpringApplication都向JVM注册了一个关闭钩，以确保ApplicationContext在退出时优雅地关闭。所有标准的Spring生命周期回调（如DisposableBean接口或@PreDestroy注解）都可以被使用。

此外，如果Bean希望在SpringApplication.exit()被调用时返回一个特定的退出代码，它们可以实现org.springframework.boot.ExitCodeGenerator接口。然后，这个退出代码可以被传递给System.exit()，将其作为状态代码返回，如下例所示。
[source,java]
----
import org.springframework.boot.ExitCodeGenerator;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class MyApplication {

    @Bean
    public ExitCodeGenerator exitCodeGenerator() {
        return () -> 42;
    }

    public static void main(String[] args) {
        System.exit(SpringApplication.exit(SpringApplication.run(MyApplication.class, args)));
    }

}
----
另外，ExitCodeGenerator接口可以由异常实现。当遇到这种异常时，Spring Boot会返回由实现的getExitCode()方法提供的退出代码。

如果有多个ExitCodeGenerator，则使用第一个生成的非零退出代码。要控制生成器的调用顺序，可以另外实现org.springframework.core.Ordered接口或使用org.springframework.core.annotation.Order注解。

==== 管理特性
通过指定spring.application.admin.enabled属性，可以启用应用程序的管理相关功能。这暴露了平台MBeanServer上的SpringApplicationAdminMXBean。你可以使用这个功能来远程管理你的Spring Boot应用程序。这个功能对任何服务封装器的实现也很有用。
====
如果你想知道应用程序是在哪个HTTP端口上运行的，可以用local.server.port的键来获取该属性。
====

==== 应用程序启动跟踪
在应用程序的启动过程中，SpringApplication和ApplicationContext执行许多与应用程序生命周期、Bean生命周期甚至处理应用程序事件有关的任务。通过ApplicationStartup，Spring框架允许你用StartupStep对象跟踪应用程序的启动顺序。这些数据可以为分析目的而收集，或者只是为了更好地了解应用程序的启动过程。

你可以在设置SpringApplication实例时选择一个ApplicationStartup实现。例如，要使用BufferingApplicationStartup，你可以这样写。

[source,java]
----
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.metrics.buffering.BufferingApplicationStartup;

@SpringBootApplication
public class MyApplication {

    public static void main(String[] args) {
        SpringApplication application = new SpringApplication(MyApplication.class);
        application.setApplicationStartup(new BufferingApplicationStartup(2048));
        application.run(args);
    }

}
----
第一个可用的实现，FlightRecorderApplicationStartup是由Spring框架提供的。它将Spring特有的启动事件添加到Java Flight Recorder会话中，旨在对应用程序进行分析，并将其Spring上下文生命周期与JVM事件（如分配、GC、类加载......）联系起来。一旦配置好，你就可以通过启用Flight Recorder运行应用程序来记录数据。
....
$ java -XX:StartFlightRecording:filename=recording.jfr,duration=10s -jar demo.jar
....

Spring Boot提供了BufferingApplicationStartup变体；该实现是为了缓冲启动步骤，并将其排入外部度量系统。应用程序可以在任何组件中要求获得BufferingApplicationStartup类型的bean。

Spring Boot也可以被配置为公开一个启动端点，以JSON文档的形式提供这一信息。
